

##################################################################################
## add different gene class types annotation: eg. TF, SM_gene etc
#' Add gene information
#'
#' @param file TAB delimited file with gene information columns. Genes are listed under
#' column 'gene'
#' @param clusterDf a dataframe to which the gene information is to be added. It should
#' have a column 'gene'
#'
#' @return A dataframe with various gene information columns added
#' @export
#'
#' @examples NA
add_gene_info = function(file, clusterDf){
  geneData = data.table::fread(input = file, header = T, drop = c(2,3),  stringsAsFactors = F, sep = "\t", data.table = F)

  clusterDf = clusterDf %>%
    dplyr::left_join(y = geneData, by = c("gene" = "gene"))

  return(clusterDf)
}

##################################################################################





##################################################################################
## get the polII expression values for list of samples
#' PolII signal list from multiple samples
#'
#' @param genesDf dataframe with gene column
#' @param exptInfo dataframe with experiment information for polII samples
#'
#' @return dataframe with polII expression and isExpressed columns for samples of interest
#' @export
#'
#' @examples NA
get_polII_expressions = function(genesDf, exptInfo){

  if(is.null(exptInfo$polIIExpFile)){
    warning("Expression data not found...")
    return(genesDf)
  }

  for(i in 1:nrow(exptInfo)){

    if(exptInfo$IP_tag[i] == "polII" & !is.na(exptInfo$polIIExpFile[i])){

      df = data.table::fread(input = exptInfo$polIIExpFile[i], header = T, stringsAsFactors = F, sep = "\t", data.table = F)
      genesDf = dplyr::left_join(x = genesDf, y = df, by = c("gene" = "gene"))

    }
  }

  return(genesDf)
}

##################################################################################






##################################################################################
## add SM_gene information to the expression profile clusterData
#' Title
#'
#' @param file file
#' @param clusterDf dataframe
#'
#' @return A dataframe
#' @export
#'
#' @examples NA
add_SM_cluster_info = function(file, clusterDf){
  smData = data.table::fread(input = file, header = T, drop = c(2,3,4,5,6,7),  stringsAsFactors = F, sep = "\t", data.table = F)
  smData$is_SM_gene = TRUE

  clusterDf = clusterDf %>%
    dplyr::left_join(y = smData, by = c("gene" = "SM_gene"))

  return(clusterDf)
}

##################################################################################




##################################################################################
## add peak region enrichment score for each gene
#' Add peak region RPM score
#'
#' @param exptInfo sample information dataframe generated by function get_sample_information()
#' @param genesDf a dataframe to which the peak region RMP score column will be added
#'
#' @return A data frame
#' @export
#'
#' @examples NA
get_peak_region_expression = function(exptInfo, genesDf){

  if(is.null(exptInfo$tfExpAtPeakFile)){
    warning("Peak region expression data not found...")
    return(genesDf)
  }


  for(i in 1:nrow(exptInfo)){
    if(exptInfo$IP_tag[i] != "polII" & !is.na(exptInfo$tfExpAtPeakFile[i])){

      title = paste("peakExpr.", exptInfo$sampleId[i], sep = "")

      df = data.table::fread(input = exptInfo$tfExpAtPeakFile[i], header = F, drop = c(1,2,3,5,6), col.names = c("gene", title),
                 stringsAsFactors = F, sep = "\t", data.table = F)

      genesDf = dplyr::left_join(x = genesDf, y = df, by = c("gene" = "gene"))

    }
  }


  return(genesDf)
}
##################################################################################




##################################################################################
## add 500bp upstream region enrichment score for each gene
#' Add 500bp upstream region RPM score
#'
#' @param exptInfo sample information dataframe generated by function get_sample_information()
#' @param genesDf a dataframe to which the peak region RPM score column will be added
#'
#' @return A data frame
#' @export
#'
#' @examples NA
get_upstream_expression = function(exptInfo, genesDf){

  if(is.null(exptInfo$tfExpAtUpstreamFile)){
    warning("Peak region expression data not found...")
    return(genesDf)
  }


  for(i in 1:nrow(exptInfo)){
    if(exptInfo$IP_tag[i] != "polII" & !is.na(exptInfo$tfExpAtUpstreamFile[i])){

      title = paste("upstreamExpr.", exptInfo$sampleId[i], sep = "")

      df = data.table::fread(input = exptInfo$tfExpAtUpstreamFile[i], header = F, drop = c(1,2,3,5,6), col.names = c("gene", title),
                 stringsAsFactors = F, sep = "\t", data.table = F)

      genesDf = dplyr::left_join(x = genesDf, y = df, by = c("gene" = "gene"))

    }
  }

  return(genesDf)
}


##################################################################################









