
#' Get DNA sequence from peak summit region
#'
#' This function extract the DNA sequence around peak summit region from narrowPeak file
#'
#' @param npFile narrowpeak file generated by macs2
#' @param id sample ID
#' @param genome BSgenome object
#' @param length Length of the region. Default: 200
#' @param columnNameWithIdPrefix Whether to modify the column names to include sampleId. If TRUE, the new column names are of format: sampleId(colName)
#'
#' @return A dataframe with three columns: name, summitRegion, summitSeq
#' @export
#'
#' @examples
#' summitSeq = get_narrowpeak_summit_seq("test.narropeak", "sampleId", BSgenome.Afumigatus.AspGD.Af293, 200)
#'
get_narrowpeak_summit_seq = function(npFile, id, genome, length = 200, columnNameWithIdPrefix = TRUE){

  cat("Extracting DNA sequences for sample", id,"\n")
  cat("\tRegion:", length, "bp around summits of file", npFile, "\n")
  cat("\tGenome:", attributes(genome)$organism, "\n")

  seqAroundSummit = round(length / 2)
  narrowpeakCols = c(signalValue = "numeric", pValue = "numeric",
                     qValue = "numeric", peak = "integer")

  np = rtracklayer::import(con = npFile, format = "bed", extraCols = narrowpeakCols)

  ## reset the start and end of the GRanges object to the region around summit position
  start(np) = BiocGenerics::start(np) + np$peak - seqAroundSummit
  end(np) = BiocGenerics::start(np) + length

  ## get the DNA sequence for region
  np$summitSeq = BSgenome::getSeq(x = genome, names = np, as.character = TRUE)

  regionCol = paste("summitRegion.", id, sep = "")
  seqCol = paste("summitSeq.", id, sep = "")

  motifSeq = BSgenome::as.data.frame(np) %>%
    dplyr::mutate(summitRegion = paste(seqnames, ":", start, "-", end, sep = "")) %>%
    dplyr::select(name, summitRegion, summitSeq) %>%
    {
      if (columnNameWithIdPrefix) {
        dplyr::rename(.,
          !! regionCol := summitRegion,
          !! seqCol := summitSeq
        )
      } else{
        .
      }
    }



  return(motifSeq)
}

