
##################################################################################
## get the TF peak data for each gene
#' Get the TF peak annotation data
#'
#' This function extract the columns from SAMPLE_ID_peaks.annotated.tab file for
#'  multiple samples and returns a dataframe.
#'
#'
#' @param genesDf Dataframe with genes of interest. Default: NULL
#' @param exptInfo Experiment information dataframe generated by get_sample_information()
#' @param allColumns Whether to get all the columns TRUE or FALSE
#'
#' @return Dataframe with all columns when allColumns is TRUE.
#' If allColumns = FALSE, "hasPeak.sampleId",  "peakId.sampleId",  "peakDist.sampleId",
#' "summitDist.sampleId",  "peakType.sampleId",   "enrichment.sampleId",  "pval.sampleId",
#' "tesPeakType.sampleId",  "tesEnrichment.sampleId",  "tesPval.sampleId"  columns are
#' returned from TF peak annotation file
#' @export
#'
#' @examples NA
get_TF_binding_data <- function(genesDf = NULL, exptInfo, allColumns = FALSE){

  if (is.null(exptInfo$tfPeakFile)) {
    warning("TF binding data not found...")
    return(genesDf)
  }

  for(i in 1:nrow(exptInfo)){
    if(exptInfo$IP_tag[i] != "polII" & !is.na(exptInfo$tfPeakFile[i])){

      if(exptInfo$TF[i] == "untagged"){
        next()
      }

      colNames <- paste(c("hasPeak.", "peakId.", "peakDist.", "summitDist.", "peakType.", "enrichment.", "peakCoverage.", "pval.", "tesPeakType.", "tesEnrichment.", "tesPval."), exptInfo$sampleId[i], sep = "")

      df <- data.table::fread(input = exptInfo$tfPeakFile[i], header = T, stringsAsFactors = F,
                             drop = c("chr", "start", "end", "strand"), sep = "\t", data.table = F)


      if(!allColumns){
        df <- df %>% dplyr::select(gene, !!!colNames)
      }

      ## join the data with genesDf is it exists
      if(is.null(genesDf)){
        # message("Using all genes from TF annotation data. not using a particular geneset.")
        genesDf <- df
      } else{
        genesDf <- left_join(x = genesDf, y = df, by = c("gene" = "gene"))
      }

    }
  }

  return(genesDf)
}

##################################################################################

