
#' Annotate peak targets in UTR regions
#'
#' @param queryGr GRanges object generated from narrowPeak or broadPeak file
#' @param subjectGrl GRangesList object for CDS generated by \code{GenomicFeatures::fiveUTRsByTranscript()}
#' or \code{GenomicFeatures::threeUTRsByTranscript()}
#' @param utrType A character string either of \code{"5UTR"} or \code{"3UTR"}. This string is added
#' as peakType column value for the peaks which overlap the respective UTR region.
#' @param txdb TxDB object
#'
#' @return A modified peak GRanges object with additional columns: \code{ tx_id,
#' peakType, featureCovFrac, peakDist, summitDist}
#' @export
#'
#' @examples NA
UTR_annotate <- function(queryGr, subjectGrl, utrType, txdb){

  if(class(subjectGrl) != "CompressedGRangesList"){
    stop("subjectGrl should be a GRangesList object")
  }

  if(! any(utrType %in% c("5UTR", "3UTR"))){
    stop("Wrong argument utrType: should be one of \"5UTR\" or \"3UTR\")")
  }

  ## remember to combine the multi-exon UTRs from UTR GRangesList
  utrGr <- unlist(range(subjectGrl))
  mcols(utrGr)$tx_id <- names(utrGr)

  utrOvlp <- GenomicRanges::findOverlaps(query = queryGr, subject = utrGr)

  queryTargets <- queryGr[utrOvlp@from]
  mcols(queryTargets)$tx_id <- mcols(utrGr)$tx_id[utrOvlp@to]
  mcols(queryTargets)$peakType <- utrType
  mcols(queryTargets)$peakDist <- 0

  ## get respective transcripts for each UTR
  ## featureCovFrac is at transcript level
  transcriptsGrl <- GenomicFeatures::mapIdsToRanges(x = txdb,
                                                    keys = list(tx_id = mcols(queryTargets)$tx_id),
                                                    type = "tx")
  transcriptGr <- unlist(transcriptsGrl)



  mcols(queryTargets)$targetStart = start(transcriptGr)
  mcols(queryTargets)$targetEnd = end(transcriptGr)
  mcols(queryTargets)$targetStrand = strand(transcriptGr)
  mcols(queryTargets)$featureCovFrac <- as.numeric(
    sprintf(fmt = "%.3f", width(pintersect(x = queryTargets, y = transcriptGr)) / width(transcriptGr))
  )

  ## calculate summit distance and change relativeSummitPos based on target gene
  ## summitDist > (targetEnd - targetStart) : peak overlap at end and summit is after end
  ## summitDist < 0 : peak overlap at start and summit before start
  utrTargetsDf <- as.data.frame(queryTargets) %>%
    dplyr::mutate(
      summitDist = dplyr::case_when(
        targetStrand == "+" ~ peakSummit - targetStart,
        targetStrand == "-" ~ targetEnd - peakSummit
      )
    ) %>%
    dplyr::mutate(
      relativeSummitPos = dplyr::case_when(
        summitDist > (targetEnd - targetStart) ~ 1,
        summitDist < 0 ~ 0,
        summitDist > 0 ~ as.numeric(sprintf("%.3f", (peakSummit - targetStart) / (targetEnd - targetStart))),
        TRUE ~ relativeSummitPos
      )
    ) %>%
    dplyr::mutate(
      relativeSummitPos = dplyr::if_else(
        condition = targetStrand == "-", true = 1 - relativeSummitPos, false = relativeSummitPos)
    )

  utrTargetsGr <- makeGRangesFromDataFrame(df = utrTargetsDf, keep.extra.columns = TRUE)
  return(utrTargetsGr)
}


##################################################################################


#' Map peaks to given GRanges regions
#'
#' This function annotates the peaks onto a regions into e.g. \code{CDS_start, CDS_end, include_CDS,
#' inside_CDS} categories.
#' In addition, relativeSummitPos value is updated w.r.t. region for the peaks which are
#' annotated as e.g. \code{inside_CDS}
#'
#' @param queryGr GRanges object generated from narrowPeak or broadPeak file
#' @param subjectGr GRanges object for regions on which peaks needs to be mapped. E.g:
#'  \code{GenomicFeatures::cdsBy()} or \code{GenomicFeatures::transcripts()}
#' @param includeFractionCut A cutoff on peak coverage value of CDS. If peak covers more
#' than this proportion of CDS, it is annotated as \code{inside_CDS}. Default: 0.7
#' @param name Feature type to be used as suffix in peak type annotation. Eg. CDS, gene etc.
#'
#' @return A modified peak GRanges object with additional columns: \code{ tx_id,
#' peakType, featureCovFrac, peakDist, summitDist}
#' @export
#'
#' @examples NA
region_overlap_annotate <- function(queryGr, subjectGr, includeFractionCut = 0.7, name = "CDS"){

  if(includeFractionCut < 0 || includeFractionCut > 1){
    stop("Invalid includeFractionCut value. Should be in range [0, 1]")
  }

  ## define feature types
  insideFeature <- paste("inside_", name, sep = "")
  includeFeature <- paste("include_", name, sep = "")
  overlapStart <- paste(name, "_start", sep = "")
  overlapEnd <- paste(name, "_end", sep = "")


  ovlpHits <- GenomicRanges::findOverlaps(query = queryGr, subject = subjectGr)

  queryTargets <- queryGr[ovlpHits@from]
  mcols(queryTargets)$tx_id <- mcols(subjectGr)$tx_id[ovlpHits@to]
  mcols(queryTargets)$peakType <- insideFeature
  mcols(queryTargets)$peakDist <- 0

  ##
  mcols(queryTargets)$targetStart = start(subjectGr[ovlpHits@to])
  mcols(queryTargets)$targetEnd = end(subjectGr[ovlpHits@to])
  mcols(queryTargets)$targetStrand = strand(subjectGr[ovlpHits@to])
  mcols(queryTargets)$featureCovFrac <- as.numeric(
    sprintf(fmt = "%.3f", width(pintersect(x = queryTargets, y = subjectGr[ovlpHits@to])) / width(subjectGr[ovlpHits@to])))

  ## assign appropriate target location
  ## if the peak is inside_CDS, update the relativeSummitPos w.r.t. CDS
  ##
  ##     |>=====>=====>======>======>======>|            |<=====<=====<======<======<======<|
  ##   -------                                                                           --------
  ##                                    -------       -------
  ##                 -------                                          --------
  ##  -------------------------------------------     -------------------------------------------
  ##
  ## calculate summit distance and change relativeSummitPos based on target gene
  targetsDf <- as.data.frame(queryTargets) %>%
    dplyr::mutate(
      peakType = dplyr::case_when(
        peakStart <= targetStart & peakEnd >= targetEnd ~ includeFeature,
        featureCovFrac >= includeFractionCut ~ includeFeature,
        targetStrand == "+" & peakStart <= targetStart & peakEnd < targetEnd ~ overlapStart,
        targetStrand == "+" & targetStart < peakStart & targetEnd <= peakEnd ~ overlapEnd,
        targetStrand == "-" & peakStart <= targetStart & peakEnd < targetEnd ~ overlapEnd,
        targetStrand == "-" & targetStart < peakStart & targetEnd <= peakEnd ~ overlapStart,
        TRUE ~ insideFeature
      )
    ) %>%
    dplyr::mutate(
      summitDist = dplyr::case_when(
        peakType != overlapEnd & targetStrand == "+" ~ peakSummit - targetStart,
        peakType != overlapEnd & targetStrand == "-" ~ targetEnd - peakSummit,
        peakType == overlapEnd & targetStrand == "+" ~ peakSummit - targetEnd,
        peakType == overlapEnd & targetStrand == "-" ~ targetStart - peakSummit
      ),
      relativeSummitPos = dplyr::if_else(
        condition = peakType == insideFeature,
        true = as.numeric(sprintf("%.3f", (peakSummit - targetStart) / (targetEnd - targetStart))),
        false = relativeSummitPos
      )
    ) %>%
    dplyr::mutate(
      relativeSummitPos = dplyr::if_else(
        condition = targetStrand == "-", true = 1 - relativeSummitPos, false = relativeSummitPos)
    )

  ## convert back to GRanges
  queryTargets <- makeGRangesFromDataFrame(df = targetsDf, keep.extra.columns = TRUE)

  return(queryTargets)
}

##################################################################################

#' Set peakType to pseudo
#'
#' @param target A dataframe or GRanges object which has peakType column
#'
#' @return Same object with \code{pseudo} prefix to peakType column values
#' @export
#'
#' @examples
set_peakTarget_to_pseudo <- function(target){
  if(any(class(target) %in% "GRanges")){
    mcols(target)$peakType <- paste("pseudo_", mcols(target)$peakType, sep = "")
  } else if(any(class(target) %in% "data.frame")){
    target$peakType <- paste("pseudo_", target$peakType, sep = "")
  }

  return(target)
}

##################################################################################


#' Annotate upstream peaks on transcripts
#'
#' @param peaksGr GRanges object for peak data
#' @param featuresGr A transcript GRanges object
#' @param txdb Optional TxDB object. A UTR less region is created using TxDB and used
#' to find the overlap between peak and its downstream target. A max fractional
#' overlap of 0.2 with geneA is allowed in a case when peak overlaps with a geneA and
#' is upstream of geneB. This is useful for the peaks which are near TES of a geneA.
#' If TxDB object is not provided, featuresGr is used. Default: featuresGr is used.
#' @param ... Other arguments for \code{nearest_upstream_bidirectional()} function
#'
#' @return A modified peak GRanges object with additional columns: \code{ tx_id,
#' peakType, featureCovFrac, peakDist, summitDist}
#' @export
#'
#' @examples NA
upstream_annotate <- function(peaksGr, featuresGr, txdb = NULL, ...){

  ## select immediate downstream feature to the peak
  peakDownFeatures <- GenomicRanges::precede(x = peaksGr, subject = featuresGr,
                                             select = "first", ignore.strand = TRUE)

  ## select the upstreamHits which have strand == "+"
  ## because peak is downstream to the feature with strand == "-"
  peakDownHits <- data.frame(
    from = 1:length(peaksGr), peakId = mcols(peaksGr)$name,
    to = peakDownFeatures, featureStrand = strand(featuresGr[peakDownFeatures]),
    txName = featuresGr$tx_name[peakDownFeatures],
    stringsAsFactors = FALSE) %>%
    dplyr::filter(featureStrand == "+")


  ## select immediate upstream feature to the peak
  peakUpFeatures <- GenomicRanges::follow(x = peaksGr, subject = featuresGr,
                                          select = "last", ignore.strand = TRUE)

  ## select the upstreamHits which have strand == "-"
  ## because peak is downstream to the feature with strand == "+"
  peakUpHits <- data.frame(
    from = 1:length(peaksGr), peakId = mcols(peaksGr)$name,
    to = peakUpFeatures, featureStrand = strand(featuresGr[peakUpFeatures]),
    txName = featuresGr$tx_name[peakUpFeatures],
    stringsAsFactors = FALSE) %>%
    dplyr::filter(featureStrand == "-")


  ## merge the putative upstream hits
  upstreamHits <- dplyr::bind_rows(peakDownHits, peakUpHits) %>%
    dplyr::arrange(from) %>%
    dplyr::mutate(id = row_number())


  ## find the number of genes between peak and its target.
  ## only those targets are true where there is no other feature inbetween
  ## build a GRanges object of the gap region between peak and target gene

  ## generate peak-target gap GRanges
  peakTargetGapsGr <- GenomicRanges::pgap(x = peaksGr[upstreamHits$from],
                                          y = featuresGr[upstreamHits$to])

  peakTargetGapsGr <- unstrand(peakTargetGapsGr)
  names(peakTargetGapsGr) <- upstreamHits$id

  ## build a subject GRanges for tx - (5UTR + 3UTR)
  ## Such custom regions are used because genes have 3' UTR. A peak in UTR region of
  ## a gene can be upstream of another gene
  txMinusUtrs <- featuresGr
  if(!is.null(txdb)){
    fiveUtrGr <- unlist(range(GenomicFeatures::fiveUTRsByTranscript(txdb)))
    threeUtrGr <- unlist(range(GenomicFeatures::threeUTRsByTranscript(txdb)))
    txMinusFiveUtr <- GenomicRanges::setdiff(x = GenomicFeatures::transcripts(txdb),
                                             y = fiveUtrGr,
                                             ignore.strand= TRUE)

    txMinusUtrs <- GenomicRanges::setdiff(x = txMinusFiveUtr,
                                          y = threeUtrGr,
                                          ignore.strand= TRUE)
  }

  ## find first overlapping gene/feature in gap GRanges
  ## no need to find all.
  featureInGap <- GenomicRanges::findOverlaps(query = peakTargetGapsGr,
                                              subject = txMinusUtrs,
                                              select = "first",
                                              ignore.strand = TRUE)

  isFeatureInBetweenDf <- data.frame(
    id = as.numeric(names(peakTargetGapsGr)),
    gapGrRow = 1:length(featureInGap),
    firstOverlapFeature = featureInGap,
    # fractionOvlp = 1,
    stringsAsFactors = FALSE
  ) %>%
    dplyr::filter(!is.na(firstOverlapFeature))

  ## calculate fraction overlap: needed for the peak which is inside a gene
  isFeatureInBetweenDf$intersectWd <- width(
    GenomicRanges::pintersect(
      x = peakTargetGapsGr[isFeatureInBetweenDf$gapGrRow],
      y = txMinusUtrs[isFeatureInBetweenDf$firstOverlapFeature],
      ignore.strand = TRUE)
  )

  isFeatureInBetweenDf$ovlpFeatureWd <- width(txMinusUtrs[isFeatureInBetweenDf$firstOverlapFeature])
  isFeatureInBetweenDf$fractionOvlp <- isFeatureInBetweenDf$intersectWd / isFeatureInBetweenDf$ovlpFeatureWd

  upstreamHitsFiltered <- dplyr::left_join(x = upstreamHits, y = isFeatureInBetweenDf, by = "id") %>%
    tidyr::replace_na(list(intersectWd = 0, ovlpFeatureWd = 0, fractionOvlp = 0)) %>%
    dplyr::filter(fractionOvlp <= 0.2)


  ## build upstream peaks data and filter unnecessary peaks where there is/are genes between peak and target
  upstreamPeaks <- peaksGr[upstreamHitsFiltered$from]

  mcols(upstreamPeaks)$tx_id <- mcols(featuresGr)$tx_id[upstreamHitsFiltered$to]
  mcols(upstreamPeaks)$peakType <- "upstream"
  mcols(upstreamPeaks)$peakDist <- GenomicRanges::distance(x = upstreamPeaks,
                                                           y = featuresGr[upstreamHitsFiltered$to])
  mcols(upstreamPeaks)$peakDist <- mcols(upstreamPeaks)$peakDist * -1

  mcols(upstreamPeaks)$targetStart = start(featuresGr[upstreamHitsFiltered$to])
  mcols(upstreamPeaks)$targetEnd = end(featuresGr[upstreamHitsFiltered$to])
  mcols(upstreamPeaks)$targetStrand = strand(featuresGr[upstreamHitsFiltered$to])

  ## calculate summit distance and change relativeSummitPos based on target gene
  upstreamPeaksDf <- as.data.frame(upstreamPeaks, stringsAsFactors = FALSE) %>%
    dplyr::mutate(
      featureCovFrac = 0,
      summitDist = dplyr::case_when(
        targetStrand == "+" ~ peakSummit - targetStart,
        targetStrand == "-" ~ targetEnd - peakSummit
      )
    ) %>%
    dplyr::mutate(
      relativeSummitPos = dplyr::if_else(
        condition = targetStrand == "-", true = 1 - relativeSummitPos, false = relativeSummitPos)
    )


  ## find pseudo_upstream targets
  bidirectionalPairs <- dplyr::group_by(upstreamPeaksDf, name) %>%
    dplyr::arrange(desc(peakDist), .by_group = T) %>%
    dplyr::mutate(n = n()) %>%
    dplyr::do(nearest_upstream_bidirectional(bdirTargets = .)) %>%
    dplyr::ungroup() %>%
    dplyr::arrange(seqnames, start) %>%
    as.data.frame() %>%
    dplyr::select(-n)

  upstreamPeaksAn <- makeGRangesFromDataFrame(bidirectionalPairs, keep.extra.columns = T)

  return(upstreamPeaksAn)

}


##################################################################################



#' True target for bidirectional peak
#'
#' This function
#'
#'     target1              peak                         target2
#'
#' ==<=====<=====<===     -------             ===>=====>=====>=====>==
#'
#'                                |
#'                    center between two targets
#'
#' True target: target1: more than 80% of the peak lies on target1 side
#'
#' @param bdirTargets A dataframe with two rows for bidirectional targets
#' @param skewFraction Minimum fraction of peak region allowed on the side of false target
#' from the midpoint of two target genes. Default: 0.2
#' @param minTSS_gapForPseudo Valid distance between two target genes TSS to mark one as psuedo
#'
#' @return Same dataframe in which peakType for one of the target is marked as pseudo
#' @export
#'
#' @examples NULL
nearest_upstream_bidirectional <- function(bdirTargets, skewFraction = 0.2, minTSS_gapForPseudo = 500){


  ##     target1              peak                         target2
  ## ==<=====<=====<===     -------             ===>=====>=====>=====>==
  ##                                |
  ##                    center between two targets
  ## True target: target1: more than 80% of the peak lies on target1 side

  if(nrow(bdirTargets) == 1){
    return(bdirTargets)
  } else if(nrow(bdirTargets) > 2){
    stop("Unhandled behaviour: 3 targets for bidirectional peaks")
  }

  if(all(bdirTargets$targetStrand %in% c("+", "-")) && bdirTargets$targetStrand[1] != bdirTargets$targetStrand[2]){

    posTg <- bdirTargets[ which(bdirTargets$targetStrand == "+"), ]
    negTg <- bdirTargets[ which(bdirTargets$targetStrand == "-"), ]

    ## gap center
    gapStart <- negTg$targetEnd
    gapEnd <- posTg$targetStart
    gapWidth <- gapEnd - gapStart
    gapCenter <- negTg$targetEnd + (gapWidth / 2)

    peakWidth <- posTg$peakEnd - posTg$peakStart
    peakFraction <- peakWidth * skewFraction


    if(gapWidth > minTSS_gapForPseudo){

      if((posTg$peakEnd - peakFraction) <= gapCenter){
        ## negative strand target is true; set positive strand target to pseudo
        posTg <- set_peakTarget_to_pseudo(target = posTg)
      } else if((posTg$peakStart + peakFraction) >= gapCenter){
        ## positive strand target is true; set negative strand target to pseudo
        negTg <- set_peakTarget_to_pseudo(target = negTg)
      }
    } else{
      ## if the distance between the TSS of two bidirectional targets < minTSS_gapForPseudo:
      ## CANNOT decide the pseudo target confidently
      if(posTg$peakEnd <= gapCenter){
        ## negative strand target is true; set positive strand target to pseudo
        posTg <- set_peakTarget_to_pseudo(target = posTg)
      } else if(posTg$peakStart >= gapCenter){
        ## positive strand target is true; set negative strand target to pseudo
        negTg <- set_peakTarget_to_pseudo(target = negTg)
      }
    }

    return(dplyr::bind_rows(posTg, negTg))

  }

  return(bdirTargets)
}


##################################################################################


#' Assign best target/s for each peak
#'
#' This function checks the different targets assigned for a peak and returns the
#' optimum target gene/s
#'
#' @param peakGr peak annotation in form of GRanges object. This is generated by
#' combining \code{UTR_annotate(), region_overlap_annotate(), upstream_annotate()}
#' functions.
#' @param insideSkewToEndCut A floating point number in range [0, 1]. If a peak is
#' present inside feature/gene and the relative summit position is > insideSkewToEndCut,
#' it is closer to the end of the feature. Default: 0.7
#' @param promoterLength Promoter length in number of nucleotides
#' @param bindingInGene Logical: whether the ChIPseq TF binds in gene body. This is
#' useful for polII ChIPseq data. Default: FALSE
#'
#' @return Same GRanges object as peakGr but with modified peakType column or excluding
#' some targets which were not optimum.
#' @export
#'
#' @examples NA
select_optimal_targets <- function(peakGr, insideSkewToEndCut = 0.7, promoterLength = 500,
                                bindingInGene = FALSE){
  ## if only one target, return as it is
  if(length(peakGr) == 1){
    return(peakGr)
  }

  ## apply various filters to select best target/s

  ## make GRangesList based on peakCategory
  typesGrl <- GenomicRanges::split(x = peakGr, f = mcols(peakGr)$peakCategory)

  peakFound <- list(
    upstreamTss = FALSE,
    nearStart = FALSE,
    nearEnd = FALSE,
    peakInFeature = FALSE,
    featureInPeak = FALSE
  )

  peakFound[names(typesGrl)] <- TRUE

  ## for nearStart peak
  if(peakFound$nearStart){

    ## 1) one target is nearStart and second target is upstreamTss
    if(peakFound$upstreamTss){
      ## decide pseudo_upstream based on nearest_upstream_bidirectional()
      bidirectDicision <- nearest_upstream_bidirectional(
        bdirTargets = as.data.frame(c(typesGrl$nearStart[1], typesGrl$upstreamTss[1])),
        minTSS_gapForPseudo = promoterLength
      )

      ## update upstreamTss peak. if it is marked as pseudo, it will be overwritten
      typesGrl$upstreamTss <- makeGRangesFromDataFrame(
        bidirectDicision[which(bidirectDicision$peakCategory == "upstreamTss"), ],
        keep.extra.columns = T
      )

      mcols(typesGrl$upstreamTss)$bidirectional <- 1

      ## upstreamTss peaks with peakDist > promoterLength: set to NULL
      if(abs(mcols(typesGrl$upstreamTss)$peakDist) > promoterLength){
        typesGrl$upstreamTss <- NULL
        peakFound$upstreamTss <- FALSE
      }
    }

    ## 2) one target is nearStart and second target is near TES: set TES target to NULL
    if(peakFound$nearEnd){
      typesGrl$nearEnd <- NULL
      peakFound$nearEnd <- FALSE
    }
  }


  ## for featureInPeak type peak
  if(peakFound$featureInPeak){
    ## 3) remove nearEnd target
    typesGrl$nearEnd <- NULL
    peakFound$nearEnd <- FALSE

    ## 4) upstreamTss peaks with peakDist < promoterLength: select; else reject
    if(peakFound$upstreamTss){
      mcols(typesGrl$upstreamTss)$bidirectional <- 2
      typesGrl$upstreamTss <- typesGrl$upstreamTss[which(abs(mcols(typesGrl$upstreamTss)$peakDist) < promoterLength)]
    }
  }


  ## for upstreamTss peak
  ## 8) two upstreamTss peaks: remove pseudo_upstream if peakDist > promoterLength
  if(length(typesGrl$upstreamTss) == 2){
    upstreamGrl <- GenomicRanges::split(x = typesGrl$upstreamTss, f = mcols(typesGrl$upstreamTss)$peakType)

    ## set pseudo_upstream peak to NULL if it far than promoterLength
    if(!is.null(upstreamGrl$pseudo_upstream)){
      if(abs(mcols(upstreamGrl$pseudo_upstream)$peakDist) > promoterLength){
        upstreamGrl$pseudo_upstream <- NULL
      }
    }

    ## rebuild the original upstreamTss GRanges
    typesGrl$upstreamTss <- unlist(upstreamGrl)
  }


  ##
  if(bindingInGene){
    ## 5) for the TF which has known binding over gene body (E.g. polII ChIP)
    ## preference is for featureInPeak. all other targets are pseudo
    if(peakFound$featureInPeak){
      typesGrl$upstreamTss <- NULL
      peakFound$upstreamTss <- FALSE
    }
  } else{

    ## for upstreamTss peak
    if(peakFound$upstreamTss){

      ## 6) if there is upstreamTss peak and also nearEnd peak,
      ## set the upstreamTss to NULL if it is far than promoterLength
      ## ELSE just set the nearEnd peak to pseudo
      if(peakFound$nearEnd){

        if(abs(mcols(typesGrl$upstreamTss)$peakDist[1]) > promoterLength){
          typesGrl$upstreamTss <- NULL
          peakFound$upstreamTss <- FALSE
        } else{
          typesGrl$nearEnd <- set_peakTarget_to_pseudo(target = typesGrl$nearEnd)
        }
      }

      ## 7) if there is upstreamTss peak and also peakInFeature type peak
      if(peakFound$peakInFeature){

        ## if upstreamTss is within promoter range
        if(abs(mcols(typesGrl$upstreamTss)$peakDist[1]) <= promoterLength){
          if(mcols(typesGrl$peakInFeature)$relativeSummitPos[1] > insideSkewToEndCut){
            ## peak lies near end for peakInFeature. set peakInFeature to pseudo
            typesGrl$peakInFeature <- set_peakTarget_to_pseudo(target = typesGrl$peakInFeature)
          } else{
            ## set upstreamTss to pseudo
            typesGrl$upstreamTss <- set_peakTarget_to_pseudo(target = typesGrl$upstreamTss)
          }
        } else{
          typesGrl$upstreamTss <- NULL
          peakFound$upstreamTss <- FALSE
        }
      }
    }
  }

  peakGr <- unlist(typesGrl, use.names = FALSE)

  return(peakGr)

}


