
#' Read peak target annotation file generated by bedtoolsClosestPeakAnnotate.pl
#' This function reads the peak target annotation file generated by bedtoolsClosestPeakAnnotate.pl.
#' It renames the peakEnrichment, peakPval and peakSummit columns as e.g. peakPval(SAMPLE_ID)
#'
#' @param title Sample name to be used in the column names
#' @param file Peak annotation file
#' @param cols A vector of column names to select from the peak annotation file
#'
#' @return A dataframe with selected columns from peak annotation file
#' @export
#'
#' @examples NA
read_peak_annotation_file = function(title, file, cols){

  peakIdCol = paste("peakId.", title, sep = "")
  fcCol = paste("enrichment.", title, sep = "")
  pvalCol = paste("pval.", title, sep = "")
  summitCol = paste("summit.", title, sep = "")

  peakAnnDf = fread(file = file, header = T, stringsAsFactors = F, sep = "\t", select = cols) %>%
    dplyr::rename(!! peakIdCol := peakId,
                  !! fcCol := peakEnrichment,
                  !! pvalCol := peakPval,
                  !! summitCol := peakSummit) %>%
    dplyr::select(peakIdCol, fcCol, pvalCol, summitCol) %>%
    dplyr::distinct()

  return(peakAnnDf)
}


